/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.garantias;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author HG
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitStyles();
        setDate();
        initContent();
        
    }
    
    private void InitStyles(){
       message.putClientProperty( "FlatLaf.styleClass", "h1" ); 
       navtext.putClientProperty( "FlatLaf.style", "font: $h3.font" );
       navtext.setForeground(Color.white);
       dateText.putClientProperty( "FlatLaf.style", "font: 24 $light.font" );
       dateText.setForeground(Color.white);
       appName.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
       appName.setForeground(Color.white);
    }
    
    private void setDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    
    private void initContent(){
        ShowJPanel(new Major());
        
    }    
        
        
    public static void ShowJPanel(JPanel p){
        p.setSize(750,430);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnMain = new javax.swing.JButton();
        BtnUsers = new javax.swing.JButton();
        BtnRegisGar = new javax.swing.JButton();
        BtnGarPen = new javax.swing.JButton();
        BtnGarApro = new javax.swing.JButton();
        BtnGarRecha = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        navtext = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 769));
        setMinimumSize(new java.awt.Dimension(1030, 669));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1020, 640));

        menu.setBackground(new java.awt.Color(0, 102, 102));

        appName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appName.setText("SureStock");

        BtnMain.setBackground(new java.awt.Color(0, 51, 51));
        BtnMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnMain.setForeground(new java.awt.Color(255, 255, 255));
        BtnMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        BtnMain.setText("Inicio");
        BtnMain.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnMain.setBorderPainted(false);
        BtnMain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnMain.setIconTextGap(20);
        BtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMainActionPerformed(evt);
            }
        });

        BtnUsers.setBackground(new java.awt.Color(0, 51, 51));
        BtnUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnUsers.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usernew.png"))); // NOI18N
        BtnUsers.setText("Usuarios");
        BtnUsers.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnUsers.setBorderPainted(false);
        BtnUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnUsers.setIconTextGap(20);
        BtnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsersActionPerformed(evt);
            }
        });

        BtnRegisGar.setBackground(new java.awt.Color(0, 51, 51));
        BtnRegisGar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRegisGar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegisGar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/questG.png"))); // NOI18N
        BtnRegisGar.setText("Registrar Garantia");
        BtnRegisGar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnRegisGar.setBorderPainted(false);
        BtnRegisGar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnRegisGar.setIconTextGap(20);
        BtnRegisGar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisGarActionPerformed(evt);
            }
        });

        BtnGarPen.setBackground(new java.awt.Color(0, 51, 51));
        BtnGarPen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnGarPen.setForeground(new java.awt.Color(255, 255, 255));
        BtnGarPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PendGa.png"))); // NOI18N
        BtnGarPen.setText("Garantias Pendientes");
        BtnGarPen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnGarPen.setBorderPainted(false);
        BtnGarPen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnGarPen.setIconTextGap(20);
        BtnGarPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarPenActionPerformed(evt);
            }
        });

        BtnGarApro.setBackground(new java.awt.Color(0, 51, 51));
        BtnGarApro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnGarApro.setForeground(new java.awt.Color(255, 255, 255));
        BtnGarApro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        BtnGarApro.setText("Garantias Aprobadas");
        BtnGarApro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnGarApro.setBorderPainted(false);
        BtnGarApro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnGarApro.setIconTextGap(20);
        BtnGarApro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarAproActionPerformed(evt);
            }
        });

        BtnGarRecha.setBackground(new java.awt.Color(0, 51, 51));
        BtnGarRecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnGarRecha.setForeground(new java.awt.Color(255, 255, 255));
        BtnGarRecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rejacted.png"))); // NOI18N
        BtnGarRecha.setText("Garantias Rechazadas");
        BtnGarRecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnGarRecha.setBorderPainted(false);
        BtnGarRecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnGarRecha.setIconTextGap(20);
        BtnGarRecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarRechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(appName))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BtnGarRecha, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnGarApro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnRegisGar, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnGarPen, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(appName)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(BtnGarRecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(BtnGarApro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(BtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(BtnRegisGar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(BtnGarPen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        header.setBackground(new java.awt.Color(0, 153, 153));

        navtext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navtext.setText("Administración - Garantias");

        dateText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateText.setText("Hoy es {dayname} {day} de {month} de {year} ");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText)
                    .addComponent(navtext))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(navtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateText)
                .addGap(39, 39, 39))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 430));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        message.setText("¡Hola bienvenido!");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(message))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(message)
                .addGap(24, 24, 24)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsersActionPerformed
        ShowJPanel(new Users());
    }//GEN-LAST:event_BtnUsersActionPerformed

    private void BtnRegisGarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisGarActionPerformed
        ShowJPanel(new RegisGarant());
    }//GEN-LAST:event_BtnRegisGarActionPerformed

    private void BtnGarPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarPenActionPerformed
        ShowJPanel(new GarantiasPend());
    }//GEN-LAST:event_BtnGarPenActionPerformed

    private void BtnGarAproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarAproActionPerformed
        
        ShowJPanel(new GarantiasApro(false));
    }//GEN-LAST:event_BtnGarAproActionPerformed

    private void BtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMainActionPerformed
        ShowJPanel(new Major());
    }//GEN-LAST:event_BtnMainActionPerformed

    private void BtnGarRechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarRechaActionPerformed
        
        ShowJPanel(new GarantiasApro(true));
    }//GEN-LAST:event_BtnGarRechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGarApro;
    private javax.swing.JButton BtnGarPen;
    private javax.swing.JButton BtnGarRecha;
    private javax.swing.JButton BtnMain;
    private javax.swing.JButton BtnRegisGar;
    private javax.swing.JButton BtnUsers;
    private javax.swing.JLabel appName;
    private javax.swing.JPanel background;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel message;
    private javax.swing.JLabel navtext;
    // End of variables declaration//GEN-END:variables
}
