/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;
import com.mycompany.garantias.DAOGarantiasImpl;
import com.mycompany.garantias.DAOUsersImpl;
import com.mycompany.garantias.Dashboard;
import com.mycompany.interfaces.DAOGarantias;
import com.mycompany.interfaces.DAOUsers;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HG
 */
public class GarantiasPend extends javax.swing.JPanel {

    /**
     * Creates new form Major
     */
    public GarantiasPend() {
        initComponents();
        LoadGarantias();
        initStyles();
        
    }
    
    private void LoadGarantias(){
        try{
            DAOGarantias dao = new DAOGarantiasImpl();
            DefaultTableModel model = (DefaultTableModel) tableGar.getModel();
            // iteramos en los elementos de la db y los listamos 
            // por cada dato agrega una fila al modelo
            dao.listar("", "garantiasregis").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));
            

        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    
}
    
    private void initStyles(){
        searchGarant.putClientProperty("JTextField.placeholderText", "Ingrese el ID de la garantia a buscar.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchGarant = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGar = new javax.swing.JTable();
        BtnDelete = new javax.swing.JButton();
        BtnDetails = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Garantias Pendientes");

        searchGarant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGarantActionPerformed(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(0, 102, 102));
        BtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Buscar");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        tableGar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Factura", "Precio product", "Cedula client", "Nombre client", "Apellido", "Telefono", "Daño"
            }
        ));
        jScrollPane1.setViewportView(tableGar);

        BtnDelete.setBackground(new java.awt.Color(0, 102, 102));
        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Borrar");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnDetails.setBackground(new java.awt.Color(0, 102, 102));
        BtnDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnDetails.setForeground(new java.awt.Color(255, 255, 255));
        BtnDetails.setText("Detalles");
        BtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BGLayout.createSequentialGroup()
                            .addComponent(BtnDetails)
                            .addGap(42, 42, 42)
                            .addComponent(BtnDelete))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(searchGarant, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BtnSearch)))
                .addGap(34, 34, 34))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchGarant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // codigo para buscar un usuario al presionar el boton.
        try{
                String garantSearch = searchGarant.getText();
                DAOGarantias dao = new DAOGarantiasImpl();
                DefaultTableModel model = (DefaultTableModel) tableGar.getModel();
                // usamos sel "setRowCount" para que nos muestre solo una columna en la busqueda
                model.setRowCount(0);
                // iteramos en los elementos de la db y los listamos 
                // por cada dato agrega una fila al modelo
                dao.listar(garantSearch, "garantiasregis").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));

            } catch(Exception e){
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void searchGarantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGarantActionPerformed
        
    }//GEN-LAST:event_searchGarantActionPerformed

    private void BtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetailsActionPerformed
         if (tableGar.getSelectedRow() > -1) {
            try{
            // si la garantia seleccionada es mayor a -1, es decir que sea desde el indice 0
            // almacenamos su "ID" en la variable "userId"
            int garantId = Integer.parseInt((String) tableGar.getValueAt(tableGar.getSelectedRow(), 0));
                System.out.println(garantId);
            // creamos el objeto dao
            DAOGarantias dao = new DAOGarantiasImpl();
            // llamamos al nuevo jFrame entregandole el user a editar
            Dashboard.ShowJPanel(new ShowGarant(dao.getGarantId(garantId, "garantiasregis")));
            }catch (Exception e){
                System.out.println(e.getMessage()); 
            }
        }else{
            // si no selecciona ninguna garantia para revisar envia un mensaje de error
             javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una garantia. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDetailsActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // creamos el objeto dao
        DAOGarantias dao = new DAOGarantiasImpl();
        DefaultTableModel model = (DefaultTableModel) tableGar.getModel();
        // si no se ha seleccionado usuario para borrar muestra mensaje de error
        if (tableGar.getSelectedRows().length < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una o más garantias  a eliminar. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            // iteramos sobre los indices de cada uno de los usuarios registrados
            for (int i : tableGar.getSelectedRows()) {
                try{
                    // obtenemos su id "cedula" almacenado en "userId"
                    int garantId = Integer.parseInt((String) tableGar.getValueAt(i, 0));          
                    // llamamos a la funcion de eliminar y le pasamos como parametro el "ID" del usuario
                    dao.eliminar(garantId, "garantiasregis");
                    // se utiliza el "removeRow" para eliminar el usuario de la tabla luego de ya haberse borrado en la bd
                    // pasando como parametro el index del usuario seleccionado
                    model.removeRow(i);
                } catch(Exception e){
                    System.out.println(e.getMessage()); 
                }
            
            }
        }    
    }//GEN-LAST:event_BtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnDetails;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchGarant;
    private javax.swing.JTable tableGar;
    // End of variables declaration//GEN-END:variables
}
