/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;
import com.mycompany.garantias.DAOGarantiasImpl;
import com.mycompany.garantias.DAOUsersImpl;
import com.mycompany.garantias.Dashboard;
import com.mycompany.interfaces.DAOGarantias;
import com.mycompany.interfaces.DAOUsers;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HG
 */
public class GarantiasApro extends javax.swing.JPanel {
    boolean isRecha = false;

   
    
     public GarantiasApro(boolean isRecha) {
        initComponents();
        LoadGarantias(isRecha);
        initStyles(isRecha);
        
    }
    
    private void LoadGarantias(boolean isRecha){
        if (!isRecha) {
                  
        try{
            DAOGarantias dao = new DAOGarantiasImpl();
            DefaultTableModel model = (DefaultTableModel) tableGarApro.getModel();
            // iteramos en los elementos de la db y los listamos 
            // por cada dato agrega una fila al modelo
            dao.listar("", "garantiaapros").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));
            

        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        }else{
            try{
            DAOGarantias dao = new DAOGarantiasImpl();
            DefaultTableModel model = (DefaultTableModel) tableGarApro.getModel();
            // iteramos en los elementos de la db y los listamos 
            // por cada dato agrega una fila al modelo
            dao.listar("", "garantiasrecha").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));
            

        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        }
    
}
    
    private void initStyles(boolean isRecha){
        searchGarant.putClientProperty("JTextField.placeholderText", "Ingrese el ID de la garantia a buscar.");
        
        if (isRecha) {
            title.setText("Garantias Rechazadas");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchGarant = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGarApro = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Garantias Aprobadas");

        searchGarant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGarantActionPerformed(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(0, 102, 102));
        BtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Buscar");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        tableGarApro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Factura", "Precio product", "Cedula client", "Nombre client", "Apellido", "Telefono", "Daño"
            }
        ));
        jScrollPane1.setViewportView(tableGarApro);

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(searchGarant, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(BtnSearch)))))
                .addGap(34, 34, 34))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title)
                .addGap(12, 12, 12)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchGarant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // codigo para buscar un usuario al presionar el boton.
        
        if (!isRecha) {

            try{
                String garantSearch = searchGarant.getText();
                DAOGarantias dao = new DAOGarantiasImpl();
                DefaultTableModel model = (DefaultTableModel) tableGarApro.getModel();
                // usamos sel "setRowCount" para que nos muestre solo una columna en la busqueda
                model.setRowCount(0);
                // iteramos en los elementos de la db y los listamos 
                // por cada dato agrega una fila al modelo
                dao.listar(garantSearch, "garantiaapros").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));

            } catch(Exception e){
                System.out.println(e.getMessage());
            }
        }else{
            try{
                String garantSearchi = searchGarant.getText();
                DAOGarantias dao = new DAOGarantiasImpl();
                DefaultTableModel model = (DefaultTableModel) tableGarApro.getModel();
                // usamos sel "setRowCount" para que nos muestre solo una columna en la busqueda
                model.setRowCount(0);
                // iteramos en los elementos de la db y los listamos 
                // por cada dato agrega una fila al modelo
                dao.listar(garantSearchi, "garantiasrecha").forEach((u)-> model.addRow(new Object[]{u.getId_garantia(), u.getFactura(), u.getPrice(), u.getUserCed(), u.getUserName(), u.getApellido(), u.getTelefono(), u.getDamag()}));

            } catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void searchGarantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGarantActionPerformed
        
    }//GEN-LAST:event_searchGarantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchGarant;
    private javax.swing.JTable tableGarApro;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
