
package com.mycompany.views;

import com.mycompany.garantias.DAOGarantiasImpl;
import com.mycompany.garantias.DAOUsersImpl;
import static com.mycompany.garantias.Dashboard.ShowJPanel;
import com.mycompany.interfaces.DAOGarantias;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.models.Garantias;
import com.mycompany.models.Users;


public class RegisGarant extends javax.swing.JPanel {
  
    

    
    public RegisGarant() {
        initComponents();
        initStyles();
      
    }
    
 

    private void initStyles(){
        cedTxt.putClientProperty("JTextField.placeholderText", "Ingrese la cedula del usuario.");
        factTxt.putClientProperty("JTextField.placeholderText", "Ingrese el numero de factura.");
        priceTxt.putClientProperty("JTextField.placeholderText", "Ingrese el precio del producto.");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        factTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pApeTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        BtnRegistro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cedTxt = new javax.swing.JTextField();
        BtnVal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        damageTxt = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setText("Registrar nueva garantia");

        jLabel2.setText("Nombre");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel4.setText("Número de factura");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Descripción del daño");

        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Télefono");

        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        BtnRegistro.setBackground(new java.awt.Color(0, 102, 102));
        BtnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistro.setText("REGISTRAR");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula del cliente");

        cedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedTxtActionPerformed(evt);
            }
        });

        BtnVal.setBackground(new java.awt.Color(0, 102, 102));
        BtnVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnVal.setForeground(new java.awt.Color(255, 255, 255));
        BtnVal.setText("Validar");
        BtnVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio del producto");

        damageTxt.setColumns(20);
        damageTxt.setRows(5);
        jScrollPane1.setViewportView(damageTxt);

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(262, 262, 262))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(226, 226, 226))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 80, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cedTxt)
                            .addComponent(nameTxt)
                            .addComponent(pApeTxt)
                            .addComponent(telTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVal)
                        .addGap(31, 31, 31)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(factTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(factTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(BtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        String factura = factTxt.getText();
        String price = priceTxt.getText();
        String id = cedTxt.getText();
        String name = nameTxt.getText();
        String pApe = pApeTxt.getText();
        String tel = telTxt.getText();
        String damag = damageTxt.getText();
        
        
        
        //validaciones para cedula
        if(id.isEmpty()|| name.isEmpty() || pApe.isEmpty() || factura.isEmpty() || price.isEmpty() || damag.isEmpty() || tel == null) {
            // si ha dejado un campo vacio sale una ventana de error
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            factTxt.requestFocus();
            return;
        }
        // instancer un nuevo usuario de la clase garantias
        // crea un nuevo objeto de tipo "Users"
        Garantias garant =  new Garantias();
        garant.setFactura(factura);
        garant.setPrice(price);
        garant.setUserCed(id);
        garant.setUserName(name);
        garant.setApellido(pApe);
        garant.setTelefono(tel);
        garant.setDamag(damag);
        
        try{
            DAOGarantias dao = new DAOGarantiasImpl();
            
            dao.registrar(garant);
            //Envia alerta de confirmacion de registro
            javax.swing.JOptionPane.showMessageDialog(this, "Garantia registrada con exito! \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //Luego del registro exitoso limpia los campos.
            cedTxt.setText("");
            nameTxt.setText("");
            pApeTxt.setText("");
            factTxt.setText("");
            priceTxt.setText("");
            telTxt.setText("");
            damageTxt.setText("");
             
  
        }catch (Exception e){
            //si ocurre un error al registrar al usuario envia mensaje en pantalla
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al registrar la garantia. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void cedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedTxtActionPerformed
       
    }//GEN-LAST:event_cedTxtActionPerformed

    private void BtnValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValActionPerformed
        String ID = cedTxt.getText();
        
        try{
            DAOUsers daoUsers = new DAOUsersImpl();
            
            // validar la existencia del usuario
            com.mycompany.models.Users currentUser = daoUsers.getUserId(Integer.parseInt(ID));
            if (currentUser == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado, porfavor revisar o registrarlo. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                cedTxt.setText("");
                nameTxt.setText("");
                pApeTxt.setText("");
                telTxt.setText("");
                cedTxt.requestFocus();
                
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario encontrado con exito! \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                nameTxt.setText(currentUser.getName());
                pApeTxt.setText(currentUser.getApellido_p());
                telTxt.setText(currentUser.getTelefono());
            }
            }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(this, "Porfavor ingresa un numero valido. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                    System.out.println(e.getMessage());
         }
        
    }//GEN-LAST:event_BtnValActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnVal;
    private javax.swing.JTextField cedTxt;
    private javax.swing.JTextArea damageTxt;
    private javax.swing.JTextField factTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField pApeTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
