
package com.mycompany.views;

import com.mycompany.garantias.DAOGarantiasImpl;
import com.mycompany.garantias.DAOUsersImpl;
import com.mycompany.garantias.Dashboard;
import static com.mycompany.garantias.Dashboard.ShowJPanel;
import com.mycompany.interfaces.DAOGarantias;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.models.Garantias;
import com.mycompany.models.Users;


public class ShowGarant extends javax.swing.JPanel {
    Garantias infoGarant;
  
    
    

    
     public ShowGarant(Garantias garant) {
        initComponents();
        initStyles(garant);
        infoGarant = garant;
      
    }
    
    
    
 

    private void initStyles(Garantias garantia){
        idGarTxt.putClientProperty("JTextField.placeholderText", "Ingrese la cedula del usuario.");
        factTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario.");
        priceTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario.");
        cedTxt.putClientProperty("JTextField.placeholderText", "Ingrese el segundo apellido del usuario.");
        nameTxt.putClientProperty("JTextField.placeholderText", "Ingrese la dirección del usuario.");
        pApeTxt.putClientProperty("JTextField.placeholderText", "Ingrese el télefono del usuario.");
        telTxt.putClientProperty("JTextField.placeholderText", "Ingrese el télefono del usuario.");
        damageTxt.putClientProperty("JTextField.placeholderText", "Ingrese el télefono del usuario.");
        
        
            idGarTxt.setText(garantia.getId_garantia());
            factTxt.setText(garantia.getFactura());
            priceTxt.setText(garantia.getPrice());
            cedTxt.setText(garantia.getUserCed());
            nameTxt.setText(garantia.getUserName());
            pApeTxt.setText(garantia.getApellido());
            telTxt.setText(garantia.getTelefono());
            damageTxt.setText(garantia.getDamag());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        factTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pApeTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        BtnAprob = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cedTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        damageTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        idGarTxt = new javax.swing.JTextField();
        BtnRecha = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setText("Garantia de:");

        jLabel2.setText("Nombre");

        nameTxt.setEditable(false);
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        factTxt.setEditable(false);

        jLabel4.setText("Número de factura");

        pApeTxt.setEditable(false);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Descripción del daño");

        telTxt.setEditable(false);
        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Télefono");

        priceTxt.setEditable(false);
        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        BtnAprob.setBackground(new java.awt.Color(0, 102, 102));
        BtnAprob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAprob.setForeground(new java.awt.Color(255, 255, 255));
        BtnAprob.setText("APROBAR");
        BtnAprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAprobActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula del cliente");

        cedTxt.setEditable(false);
        cedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio del producto");

        damageTxt.setEditable(false);
        damageTxt.setColumns(20);
        damageTxt.setRows(5);
        jScrollPane1.setViewportView(damageTxt);

        jLabel1.setText("ID de Garantia");

        idGarTxt.setEditable(false);
        idGarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idGarTxtActionPerformed(evt);
            }
        });

        BtnRecha.setBackground(new java.awt.Color(255, 0, 0));
        BtnRecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRecha.setForeground(new java.awt.Color(255, 255, 255));
        BtnRecha.setText("RECHAZAR");
        BtnRecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(268, 268, 268))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(232, 232, 232))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pApeTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cedTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(factTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(priceTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(idGarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(BtnAprob, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(factTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idGarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnAprob, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRecha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void BtnAprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAprobActionPerformed
        int id_garant = Integer.parseInt(idGarTxt.getText());
        System.out.println(id_garant);
        String factura = factTxt.getText();
        String price = priceTxt.getText();
        String id = cedTxt.getText();
        String name = nameTxt.getText();
        String pApe = pApeTxt.getText();
        String tel = telTxt.getText();
        String damag = damageTxt.getText();
        
        
        
        //validaciones para cedula
        if(id.isEmpty()|| name.isEmpty() || pApe.isEmpty() || factura.isEmpty() || price.isEmpty() || damag.isEmpty() || tel == null) {
            // si ha dejado un campo vacio sale una ventana de error
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            factTxt.requestFocus();
            return;
        }
        // instancer un nuevo usuario de la clase garantias
        // crea un nuevo objeto de tipo "Garantias"
        Garantias garant =  new Garantias();
        garant.setFactura(factura);
        garant.setPrice(price);
        garant.setUserCed(id);
        garant.setUserName(name);
        garant.setApellido(pApe);
        garant.setTelefono(tel);
        garant.setDamag(damag);
        
        try{
            DAOGarantias dao = new DAOGarantiasImpl();
            
            dao.apobGar(garant, "garantiaapros");
            
            //Envia alerta de confirmacion de registro
            javax.swing.JOptionPane.showMessageDialog(this, "Garantia aprobada con exito! \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //Luego del registro exitoso limpia los campos.
            cedTxt.setText("");
            nameTxt.setText("");
            pApeTxt.setText("");
            factTxt.setText("");
            priceTxt.setText("");
            telTxt.setText("");
            damageTxt.setText("");
            dao.eliminar(id_garant,"garantiasregis");
             
  
        }catch (Exception e){
            //si ocurre un error al registrar al usuario envia mensaje en pantalla
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al registrar la garantia. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_BtnAprobActionPerformed

    private void cedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedTxtActionPerformed
       
    }//GEN-LAST:event_cedTxtActionPerformed

    private void BtnRechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRechaActionPerformed
        int id_garant = Integer.parseInt(idGarTxt.getText());
        System.out.println(id_garant);
        String factura = factTxt.getText();
        String price = priceTxt.getText();
        String id = cedTxt.getText();
        String name = nameTxt.getText();
        String pApe = pApeTxt.getText();
        String tel = telTxt.getText();
        String damag = damageTxt.getText();
        
        
        
        //validaciones para los campos
        if(id.isEmpty()|| name.isEmpty() || pApe.isEmpty() || factura.isEmpty() || price.isEmpty() || damag.isEmpty() || tel == null) {
            // si ha dejado un campo vacio sale una ventana de error
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            factTxt.requestFocus();
            return;
        }
        // instancer un nuevo usuario de la clase garantias
        // crea un nuevo objeto de tipo "Users"
        Garantias garant =  new Garantias();
        garant.setFactura(factura);
        garant.setPrice(price);
        garant.setUserCed(id);
        garant.setUserName(name);
        garant.setApellido(pApe);
        garant.setTelefono(tel);
        garant.setDamag(damag);
        
        try{
            DAOGarantias dao = new DAOGarantiasImpl();
            
            dao.apobGar(garant, "garantiasrecha");
            
            //Envia alerta de confirmacion de registro
            javax.swing.JOptionPane.showMessageDialog(this, "Garantia rechazada con exito! \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //Luego del registro exitoso limpia los campos.
            cedTxt.setText("");
            nameTxt.setText("");
            pApeTxt.setText("");
            factTxt.setText("");
            priceTxt.setText("");
            telTxt.setText("");
            damageTxt.setText("");
            dao.eliminar(id_garant, "garantiasregis");
             
  
        }catch (Exception e){
            //si ocurre un error al registrar al usuario envia mensaje en pantalla
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al registrar la garantia. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnRechaActionPerformed

    private void idGarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idGarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idGarTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnAprob;
    private javax.swing.JButton BtnRecha;
    private javax.swing.JTextField cedTxt;
    private javax.swing.JTextArea damageTxt;
    private javax.swing.JTextField factTxt;
    private javax.swing.JTextField idGarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField pApeTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
