
package com.mycompany.views;

import com.mycompany.garantias.DAOUsersImpl;
import static com.mycompany.garantias.Dashboard.ShowJPanel;
import com.mycompany.interfaces.DAOUsers;
import com.mycompany.models.Users;


public class UpUsers extends javax.swing.JPanel {
    // variable booleana goblar que verifica si es una edicion o no
    boolean isEdition = false;
    com.mycompany.models.Users userEdition;
    

    
    public UpUsers() {
        initComponents();
        initStyles();
      
    }
    
    public UpUsers(com.mycompany.models.Users  user ){
        // atributos declarados cuando se hace una EDICIOn de usuario
        initComponents();
        isEdition = true;
        // se almacena el usuario recibido como parametro en la variable global
        userEdition = user;
        initStyles(); 
        
    }    

    private void initStyles(){
        cedTxt.putClientProperty("JTextField.placeholderText", "Ingrese la cedula del usuario.");
        nameTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario.");
        pApeTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario.");
        sApeTxt.putClientProperty("JTextField.placeholderText", "Ingrese el segundo apellido del usuario.");
        direcTxt.putClientProperty("JTextField.placeholderText", "Ingrese la dirección del usuario.");
        telTxt.putClientProperty("JTextField.placeholderText", "Ingrese el télefono del usuario.");
        
        // si "isEdition" es true, se trata de una edicion de usuario
        // si es asi, editamos el texto del jlabel titulo y el del boton
        if (isEdition) {
            title.setText("Editar usuario");
            BtnRegistro.setText("Guardar");
            
            // si el usuario recibido como parametro no es nulo
            if (userEdition != null) {
                // rellenamos todos los textFields con los datos del usuario a editar
                cedTxt.setText(userEdition.getId_users());
                nameTxt.setText(userEdition.getName());
                pApeTxt.setText(userEdition.getApellido_p());
                sApeTxt.setText(userEdition.getApellido_m());
                direcTxt.setText(userEdition.getDireccion());
                telTxt.setText(userEdition.getTelefono());
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sApeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pApeTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direcTxt = new javax.swing.JTextField();
        BtnRegistro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cedTxt = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        title.setText("Registrar nuevo usuario");

        jLabel2.setText("Nombre");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Primer apellido");

        jLabel4.setText("Segundo apellido");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Dirección");

        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Télefono");

        direcTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direcTxtActionPerformed(evt);
            }
        });

        BtnRegistro.setBackground(new java.awt.Color(0, 102, 102));
        BtnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistro.setText("REGISTRAR");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula");

        cedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(205, 205, 205))
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(169, 169, 169))
                            .addComponent(pApeTxt)
                            .addComponent(nameTxt)
                            .addComponent(cedTxt)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(199, 199, 199))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(203, 203, 203))
                    .addComponent(direcTxt)
                    .addComponent(BtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sApeTxt)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(157, 157, 157))
                    .addComponent(telTxt))
                .addGap(44, 44, 44))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(BtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pApeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void direcTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direcTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direcTxtActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        String id = cedTxt.getText();
        String name = nameTxt.getText();
        String pApe = pApeTxt.getText();
        String sApe = sApeTxt.getText();
        String direc = direcTxt.getText();
        String tel = telTxt.getText();
        
        
        
        //validaciones para cedula
        if(id.isEmpty()|| name.isEmpty() || pApe.isEmpty() || sApe.isEmpty() || direc.isEmpty() || tel == null) {
            // si ha dejado un campo vacio sale una ventana de error
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            cedTxt.requestFocus();
            return;
        }
        // instancer un nuevo usuario de la clase users 
        // se verifica si se trata de una edicion de usuario
        // si lo es se le asigna al "user" lo que contenga la variable global userEdition
            // si no 
            // crea un nuevo objeto de tipo "Users"
        com.mycompany.models.Users user = isEdition ? userEdition : new com.mycompany.models.Users();
        user.setId_users(id);
        user.setName(name);
        user.setApellido_p(pApe);
        user.setApellido_m(sApe);
        user.setDireccion(direc);
        user.setTelefono(tel);
        
        try{
            DAOUsers dao = new DAOUsersImpl();
            
            // verifica si es una edicion de usuario
            // si no es una edicion, llama al metodo de registrar usuario
            if (!isEdition) {
             dao.registrar(user);
            // si es true
            // llama al metodo de modificar usuario
            }else
                dao.modificar(user);
                        
            // se verifica si es una edicion para cambiar el contenido de la alerta enviada.
            String succesMsg  = isEdition ? "modificado" : "registrado";
            //Envia alerta de confirmacion de registro
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario "+ succesMsg + " con exito! \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            //si se trata de un registro limpia los campos de texto
                //si no
                //deja los datos del usuario a editar
            if (!isEdition) {
            cedTxt.setText("");
            nameTxt.setText("");
            pApeTxt.setText("");
            sApeTxt.setText("");
            direcTxt.setText("");
            telTxt.setText("");
             }
  
        }catch (Exception e){
            // se verifica si es una edicion para cambiar el contenido de la alerta enviada.
            String errorMsg  = isEdition ? "modificar" : "registrar";
            //si ocurre un error al registrar al usuario envia mensaje en pantalla
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrio un error al "+errorMsg+" el usuario. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void cedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JTextField cedTxt;
    private javax.swing.JTextField direcTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField pApeTxt;
    private javax.swing.JTextField sApeTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
