/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;
import com.mycompany.garantias.DAOUsersImpl;
import com.mycompany.garantias.Dashboard;
import com.mycompany.interfaces.DAOUsers;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HG
 */
public class Users extends javax.swing.JPanel {

    /**
     * Creates new form Major
     */
    public Users() {
        initComponents();
        LoadUsers();
        initStyles();
        
    }
    
    private void LoadUsers(){
        try{
            DAOUsers dao = new DAOUsersImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            // iteramos en los elementos de la db y los listamos 
            // por cada dato agrega una fila al modelo
            dao.listar("").forEach((u)-> model.addRow(new Object[]{u.getId_users(), u.getName(), u.getApellido_p(), u.getApellido_m(), u.getDireccion(), u.getTelefono()}));
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void initStyles(){
        searchUser.putClientProperty("JTextField.placeholderText", "Ingrese la cedula del usuario a buscar.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchUser = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnDelete = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnCrearUser = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setMinimumSize(new java.awt.Dimension(750, 430));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Usuarios");

        searchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserActionPerformed(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(0, 102, 102));
        BtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Buscar");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "P. Apellido", "S. Apellido", "Dirección", "Télefono"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnDelete.setBackground(new java.awt.Color(0, 102, 102));
        BtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Borrar");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnEdit.setBackground(new java.awt.Color(0, 102, 102));
        BtnEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnEdit.setForeground(new java.awt.Color(255, 255, 255));
        BtnEdit.setText("Editar");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnCrearUser.setBackground(new java.awt.Color(0, 102, 102));
        BtnCrearUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCrearUser.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearUser.setText("Crear");
        BtnCrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(BtnCrearUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BGLayout.createSequentialGroup()
                        .addComponent(searchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BGLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(629, 629, 629)))
                .addGap(34, 34, 34))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(searchUser))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCrearUser, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // codigo para buscar un usuario al presionar el boton.
        try{
            String userSearch = searchUser.getText();
            DAOUsers dao = new DAOUsersImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            // usamos sel "setRowCount" para que nos muestre solo una columna en la busqueda
            model.setRowCount(0);
            // iteramos en los elementos de la db y los listamos 
            // por cada dato agrega una fila al modelo
            dao.listar(userSearch).forEach((u)-> model.addRow(new Object[]{u.getId_users(), u.getName(), u.getApellido_p(), u.getApellido_m(), u.getDireccion(), u.getTelefono()}));
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void searchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserActionPerformed
        
    }//GEN-LAST:event_searchUserActionPerformed

    private void BtnCrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUserActionPerformed
        Dashboard.ShowJPanel(new UpUsers());
    }//GEN-LAST:event_BtnCrearUserActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // creamos el objeto dao
        DAOUsers dao = new DAOUsersImpl();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // si no se ha seleccionado usuario para borrar muestra mensaje de error
        if (jTable1.getSelectedRows().length < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más usuarios  a eliminar. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            // iteramos sobre los indices de cada uno de los usuarios registrados
            for (int i : jTable1.getSelectedRows()) {
                try{
                    // obtenemos su id "cedula" almacenado en "userId"
                    int userId = Integer.parseInt((String) jTable1.getValueAt(i, 0));          
                    // llamamos a la funcion de eliminar y le pasamos como parametro el "ID" del usuario
                    dao.eliminar(userId);
                    // se utiliza el "removeRow" para eliminar el usuario de la tabla luego de ya haberse borrado en la bd
                    // pasando como parametro el index del usuario seleccionado
                    model.removeRow(i);
                } catch(Exception e){
                    System.out.println(e.getMessage()); 
                }
            
            }
        }    
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            try{
            // si el usuario seleccionado es mayor a -1, es decir que sea desde el indice 0
            // almacenamos su "ID" en la variable "userId"
            int userId = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            // creamos el objeto dao
            DAOUsers dao = new DAOUsersImpl();
            // llamamos al nuevo jFrame entregandole el user a editar
            Dashboard.ShowJPanel(new UpUsers(dao.getUserId(userId)));
            //String data = dao.getUserId(userId).getId_users());
            }catch (Exception e){
                System.out.println(e.getMessage()); 
            }
        }else{
            // si no selecciona ningun usuario para editar envia un mensaje de error
             javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar el usuario a editar. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton BtnCrearUser;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchUser;
    // End of variables declaration//GEN-END:variables
}
